### PR TITLE
Mdsvex integrated

### PR DESCRIPTION
**Pull request by riziles**
Added MDsveX, Tailwind Typography, remark-math, rehype-KaTeX and a css file that MDsveX uses for syntax highlighting.

### CODE REVIEW

**Comment by bennymi** [comment]
@riziles thanks for the PR. Just two comments: I think we can remove the `svhighlight-code.ts` file, that's from the previous slide, and maybe we can also mention MDSveX in the markdown title. Something like this:
`# We even got Markdown (thanks to [MDSveX](https://mdsvex.pngwn.io/))!`

Other than that it looks good. I got some error on Vercel which might be because of an `npm` install instead of `pnpm`, but I'm not entirely sure to be honest. See if using `pnpm` removes it, and I'll have another look at it later.

**Comment by riziles** [comment]
D'oh. I spelled pngwn wrong in the commit note.

**Comment by bennymi** [comment]
Hey @riziles, thanks for making the changes. One more request, can you delete the `package-lock.json` file as well? It was created by `npm`. I'll create a contribution guide later that tells people to use `pnpm` when installing the dependencies. After deleting the file you can mark the PR as ready for review and I'll merge it

**Comment by bennymi** [comment]
PR relates to #14

**Comment by riziles** [comment]
Was getting an error message in VS Code (even though everything was building fine): 

```Cannot find module './Test.md' or its corresponding type declarations``` 

Adding `globals.d.ts` made it go away. Found the solve here: <https://github.com/pngwn/MDsveX/discussions/369>

**Review by bennymi — APPROVED** [review]
Looks good to me!

**Pull request merged**
